class OAuth2Error(Exception):...


class OAuth2TokenError(OAuth2Error):...


class OAuth2TokenExpired(OAuth2TokenError):...


class OAuth2TokenInvalid(OAuth2TokenError):...


class OAuth2TokenRevoked(OAuth2TokenError):...
