class OAuth2Exception(Exception):...


class OAuth2TokenException(OAuth2Exception):...


class OAuth2TokenExpired(OAuth2TokenException):...


class OAuth2TokenInvalid(OAuth2TokenException):...


class OAuth2TokenRevoked(OAuth2TokenException):...
